driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.5.1
  data_path: test/fixtures

transport:
  compression: none

platforms:
  - name: centos-6.5
    driver_config:
      customize:
        memory: 1024

suites:
  - name: monolithic
    run_list:
      - recipe[abiquo::default]
      - recipe[abiquo::upgrade]
  - name: remoteservices
    run_list:
      - recipe[abiquo::default]
      - recipe[abiquo::upgrade]
    attributes:
      abiquo:
        profile: remoteservices
  - name: kvm
    run_list:
      - recipe[abiquo::default]
      - recipe[abiquo::upgrade]
    attributes:
      abiquo:
        profile: kvm
  - name: monitoring
    run_list:
      - recipe[abiquo::default]
    attributes:
      abiquo:
        profile: monitoring
