driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.16.4
  data_path: test/fixtures

transport:
  compression: none

platforms:
  - name: chef/centos-6.5
    driver_config:
      customize:
        memory: 1024
    run_list:
      - recipe[abiquo::default]
      - recipe[abiquo::upgrade]

suites:
  - name: monolithic
  - name: remoteservices
    attributes:
      abiquo:
        profile: remoteservices
  - name: kvm
    attributes:
      abiquo:
        profile: kvm
  - name: monitoring
    run_list:
      - recipe[abiquo::default]
    attributes:
      abiquo:
        profile: monitoring
