platforms:
  - name: centos-6.5
    driver_config:
      customize:
        memory: 1024
    attributes:
      abiquo:
        yum:
          nightly-repo: http://10.60.20.42/<%= ENV['CI_BRANCH']%>/rpm
