driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1
  data_path: test/fixtures

transport:
  compression: none

platforms:
  - name: centos-6.8

suites:
  - name: monolithic
    run_list:
      - recipe[abiquo::default]
      - recipe[abiquo::upgrade]
    attributes:
      set_fqdn: monolithic.abiquo.com
      abiquo:
        ui_address_type: set_fqdn
        ui_apache_opts:
          KeepAlive: "On"
          MaxKeepAliveRequests: 100
          KeepAliveTimeout: 60
        ui_proxies:
          /am2: http://some_am:8009/am
        certificate:
          common_name: monolithic.abiquo.com
  - name: server
    run_list:
      - recipe[abiquo::default]
      - recipe[abiquo::upgrade]
    attributes:
      set_fqdn: server.abiquo.com
      abiquo:
        profile: server
        ui_address_type: set_fqdn
        ui_config:
          client.backto.url: "http://google.com"
          client.google.maps.key: "trocotro"
          client.test.timeout: 600
        ui_apache_opts:
          KeepAlive: "On"
          MaxKeepAliveRequests: 100
          KeepAliveTimeout: 60
        ui_proxies:
          /am2: http://some_am:8009/am
        certificate:
          common_name: server.abiquo.com
  - name: ui
    run_list:
      - recipe[abiquo::default]
      - recipe[abiquo::upgrade]
    attributes:
      set_fqdn: server.abiquo.com
      abiquo:
        profile: ui
        ui_address_type: set_fqdn
        ui_config:
          client.backto.url: "http://google.com"
          client.google.maps.key: "trocotro"
          client.test.timeout: 600
        certificate:
          common_name: server.abiquo.com
  - name: websockify
    run_list:
      - recipe[abiquo::default]
      - recipe[abiquo::upgrade]
    attributes:
      set_fqdn: ws.abiquo.com
      abiquo:
        profile: websockify
        certificate:
          common_name: ws.abiquo.com
  - name: remoteservices
    run_list:
      - recipe[abiquo::default]
      - recipe[abiquo::upgrade]
    attributes:
      abiquo:
        profile: remoteservices
  - name: v2v
    run_list:
      - recipe[abiquo::default]
      - recipe[abiquo::upgrade]
    attributes:
      abiquo:
        profile: v2v
  - name: kvm
    run_list:
      - recipe[abiquo::default]
      - recipe[abiquo::upgrade]
    attributes:
      abiquo:
        profile: kvm
  - name: monitoring
    run_list:
      # The Delorean service needs a running RabbitMQ instance
      - recipe[abiquo::repository]
      - recipe[rabbitmq]
      - recipe[abiquo::default]
      - recipe[abiquo::upgrade]
    attributes:
      abiquo:
        profile: monitoring
      rabbitmq:
        version: 3.5.4
