driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.16.4

platforms:
  - name: chef/centos-6.5

suites:
  - name: monolithic
    run_list:
      - recipe[abiquo::default]
      - recipe[abiquo::upgrade]
    attributes:
      abiquo:
        yum:
          base-repo: "http://mirror.bcn.abiquo.com/abiquo/3.4/os/x86_64"
          updates-repo: "http://mirror.bcn.abiquo.com/abiquo/3.4/os/x86_64"
  - name: remoteservices
    run_list:
      - recipe[abiquo::default]
      - recipe[abiquo::upgrade]
    attributes:
      abiquo:
        profile: remoteservices
        yum:
          base-repo: "http://mirror.bcn.abiquo.com/abiquo/3.4/os/x86_64"
          updates-repo: "http://mirror.bcn.abiquo.com/abiquo/3.4/os/x86_64"
  - name: kvm
    run_list:
      - recipe[abiquo::default]
      - recipe[abiquo::upgrade]
    attributes:
      abiquo:
        profile: kvm
        yum:
          base-repo: "http://mirror.bcn.abiquo.com/abiquo/3.4/os/x86_64"
          updates-repo: "http://mirror.bcn.abiquo.com/abiquo/3.4/os/x86_64"
