driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.5.1
  data_path: test/fixtures

transport:
  compression: none

platforms:
  - name: centos-6.7
    driver_config:
      customize:
        memory: 1024

suites:
  - name: monolithic
    run_list:
      - recipe[abiquo::default]
      - recipe[abiquo::upgrade]
    attributes:
      set_fqdn: monolithic.abiquo.com
      abiquo:
        profile: monolithic
        ui_address_type: set_fqdn
        certificate:
          common_name: monolithic.abiquo.com
  - name: server
    run_list:
      - recipe[abiquo::default]
      - recipe[abiquo::upgrade]
    attributes:
      set_fqdn: server.abiquo.com
      abiquo:
        profile: server
        ui_address_type: set_fqdn
        certificate:
          common_name: server.abiquo.com
  - name: remoteservices
    run_list:
      - recipe[abiquo::default]
      - recipe[abiquo::upgrade]
    attributes:
      abiquo:
        profile: remoteservices
  - name: v2v
    run_list:
      - recipe[abiquo::default]
      - recipe[abiquo::upgrade]
    attributes:
      abiquo:
        profile: v2v
  - name: kvm
    run_list:
      - recipe[abiquo::default]
      - recipe[abiquo::upgrade]
    attributes:
      abiquo:
        profile: kvm
  - name: monitoring
    run_list:
      - recipe[abiquo::default]
    attributes:
      abiquo:
        profile: monitoring
  - name: lwrp
    run_list:
      - recipe[abiquo::default]
      - recipe[abiquo::install_kvm]
      - recipe[abiquo::setup_kvm]
      - recipe[abiquo::upgrade]
      - recipe[abiquo_test::default]
    attributes:
      set_fqdn: monolithic.abiquo.com
      abiquo:
        tomcat:
          wait-for-webapps: true
        profile: monolithic
        ui_address_type: set_fqdn
        properties:
          abiquo.datacenter.id: test
          abiquo.virtualfactory.kvm.fullVirt: false
          abiquo.appliancemanager.repositoryLocation: "127.0.1.1:/opt/vm_repository"
          abiquo.appliancemanager.checkMountedRepository: false
