driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.16.4

platforms:
  - name: centos-6.5

suites:
  - name: monolithic
    run_list:
      - recipe[abiquo::default]
      - recipe[abiquo::upgrade]
    attributes:
      abiquo:
        yum:
          nightly-repo: http://10.60.20.42/master/rpm
  - name: remoteservices
    run_list:
      - recipe[abiquo::default]
      - recipe[abiquo::upgrade]
    attributes:
      abiquo:
        profile: remoteservices
        yum:
          nightly-repo: http://10.60.20.42/master/rpm
  - name: kvm
    run_list:
      - recipe[abiquo::default]
      - recipe[abiquo::upgrade]
    attributes:
      abiquo:
        profile: kvm
        yum:
          nightly-repo: http://10.60.20.42/master/rpm
