LineLength:
  Max: 250

IndentationWidth:
  Width: 4

Style/Documentation:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: hash_rockets
Style/NumericLiterals:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Max: 50
