name             'abiquo'
maintainer       'Abiquo'
maintainer_email 'ignasi.barrera@abiquo.com'
license          'Apache 2.0'
description      'Installs and configures an Abiquo platform'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

recipe 'abiquo', 'Installs and configures an Abiquo platform'
recipe 'abiquo::repository', 'Configures the Abiquo yum repositories'
recipe 'abiquo::install_monolithic', 'Installs the Abiquo Monolithic packages'
recipe 'abiquo::install_remoteservices', 'Installs and configures the Abiquo Remote Services'
recipe 'abiquo::setup_server', 'Configures and starts the Abiquo Server'
recipe 'abiquo::setup_remoteservices', 'Configures and starts the Abiquo Remote Services'
recipe 'abiquo::update', 'Updates the platform to the latest packages'
recipe 'abiquo::database', 'Creates the Abiquo database'
recipe 'abiquo::certificate', 'Installs a custom SSL certificate in the Apache'
recipe 'abiquo::stop', 'Stops all Abiquo services'
recipe 'abiquo::start', 'Starts all Abiquo services'

supports 'centos', '>= 6.0'

depends 'apache2'
depends 'iptables'
depends 'java'
depends 'java-management'
depends 'redisio'
depends 'selfsigned_certificate'
depends 'selinux'
depends 'yum'
